[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "ls -la frontend/",
  "cd frontend && ls -la",
  "cd frontend && npm install --production=false",
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npm start" 