[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "find . -name 'index.html' -type f",
  "ls -la frontend/public/",
  "cd frontend && ls -la",
  "cd frontend && ls -la public/",
  "cd frontend && cat public/index.html",
  "cd frontend && npm install --production=false",
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && ls -la && npm install && ls -la node_modules && npm start" 